// ── "TIME TO CHOOSE" STATEMENTS ──────────────────────────────────────────────
// Same pattern as questions.js: a plain list of objects in its own file.
//   { text: <påståendet spelarna röstar på> }
// Rundan shufflar dem och cyklar igenom.
//
// OBS: 18+ / vuxenversion — snuskiga "vem av oss skulle..."-påståenden. Byt
// tillbaka till en snällare lista om ni kör med blandat sällskap.

module.exports = [
  { text: 'Vem av oss skulle skicka nudes utan att blinka?' },
  { text: 'Vem av oss skulle ha en crush på den mest otippade läraren? (Även flera år senare!)' },
  { text: 'Vem av oss skulle ragga med en usel raggningsreplik... och lyckas?' },
  { text: 'Vem av oss skulle ha ett regelbundet KK och hantera det helt utan känslor?' },
  { text: 'Vem av oss skulle testa en helt akrobatisk ställning från Kama Sutra (och kanske sträcka en muskel)?' },
  { text: 'Vem av oss skulle improvisera en striptease (även bara på skoj)?' },
  { text: 'Vem av oss skulle ha den mest imponerande (eller konstigaste) samlingen sexleksaker?' },
  { text: 'Vem av oss skulle skaffa en dejtingapp bara för att hitta ett one-night stand?' },
  { text: 'Vem av oss skulle i hemlighet fantisera om någon i det här rummet? (Ouhhh...)' },
  { text: 'Vem av oss skulle redan ha blivit påkommen mitt i akten? (Berätta!)' },
  { text: 'Vem av oss skulle föra en "ligglista" (även om det inte är så snyggt)?' },
  { text: 'Vem av oss skulle våga föreslå (eller tacka ja till) en trekant?' },
  { text: 'Vem av oss skulle titta på porr helt öppet?' },
  { text: 'Vem av oss skulle ha den mest pinsamma sexrelaterade historien att berätta?' },
  { text: 'Vem av oss skulle bli kär efter en enda het natt?' },
  { text: 'Vem av oss skulle redan ha överdrivit (lite mycket) sina prestationer i sängen?' },
  { text: 'Vem av oss skulle säga att de föredrar förspel framför samlag?' },
  { text: 'Vem av oss skulle klara sig längst utan sex... och bli superirriterad?' },
  { text: 'Vem av oss skulle ha en väldigt specifik och lite oväntad "typ"?' },
  { text: 'Vem av oss skulle skicka snuskiga meddelanden under ett jobbmöte (eller en lektion)?' },
  { text: 'Vem av oss skulle falla för någon som är mycket äldre (eller mycket yngre)?' },
  { text: 'Vem av oss skulle redan ha använt accessoarer som handbojor eller ögonbindel?' },
  { text: 'Vem av oss skulle vara högljuddast under sex?' },
  { text: 'Vem av oss skulle ha en riktigt snuskig hemlighet (som man kanske kan erkänna ikväll...)?' },
  { text: 'Vem av oss skulle gilla att bli dominerad (eller tvärtom, dominera) i sängen?' },
  { text: 'Vem av oss skulle ha haft en homosexuell upplevelse bara av nyfikenhet?' },
  { text: 'Vem av oss skulle ha en tatuering eller piercing på ett väldigt... dolt ställe?' },
  { text: 'Vem av oss skulle skamlöst erkänna att man har fejkat en orgasm?' },
  { text: 'Vem av oss skulle ha haft flest olika sexpartners?' },
  { text: 'Vem av oss skulle våga föreslå en snuskig lek offentligt (diskret, såklart)?' },
  { text: 'Vem av oss skulle ha haft sex på en ovanlig offentlig plats (stranden, bilen, en park...)?' },
  { text: 'Vem av oss skulle ha en fantasi som involverar en uniform (brandman, sjuksköterska...)?' },
  { text: 'Vem av oss skulle vara bäst på sensuell massage?' },
  { text: 'Vem av oss skulle ha haft en helt virtuell relation?' },
  { text: 'Vem av oss skulle ha mest snuskigt skvaller om de andra i gruppen? (Se upp...)' },
  { text: 'Vem av oss skulle gilla att bli fotad eller filmad under akten?' },
  { text: 'Vem av oss skulle ha ljugit om sitt antal partners?' },
  { text: 'Vem av oss skulle vara mest bekväm med att prata öppet om sex?' },
  { text: 'Vem av oss skulle ha ett "safe word"?' },
  { text: 'Vem av oss skulle ha haft en könssjukdom (och prata öppet om det för att förebygga)?' },
  { text: 'Vem av oss skulle föredra en snabb och intensiv omgång framför en lång och sensuell?' },
  { text: 'Vem av oss skulle ha varit på en swingersklubb (eller skulle vilja testa)?' },
  { text: 'Vem av oss skulle ha ett altare tillägnat ett ex? (Okej, mer creepy än hett – men det kan spåra ur)' },
  { text: 'Vem av oss skulle gilla lätta bett eller rivmärken under sex?' },
  { text: 'Vem av oss skulle ha skrivit eller läst erotiska fanfictions?' },
  { text: 'Vem av oss skulle ha flest sexiga underkläder?' },
  { text: 'Vem av oss skulle ha stött på sitt ex bästa vän?' },
  { text: 'Vem av oss skulle mest troligt skrika fel namn vid fel tillfälle?' },
  { text: 'Vem av oss skulle ha en "typ" baserad enbart på en kroppsdel (händer, ögon, rumpa...)?' },
  { text: 'Vem av oss skulle ha betalat för sex (eller övervägt att göra det)?' },
];
